version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/yoheimuta/xo-example-app
    steps:
      - checkout
      - run: make dev/install/dep
      - run: make test/lint
  test:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/yoheimuta/xo-example-app
    steps:
      - checkout
      - run:
          name: "setup"
          command: |
            docker run --name test-mysql --rm -d -e MYSQL_ROOT_PASSWORD=my-pw -p 3306:3306 mysql:8.0.0
      - run:
          name: "test"
          command: |
            make dev/test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test

